//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CricketStats.Datalayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BowlingInn
    {
        public System.Guid bowlingInnsid { get; set; }
        public System.Guid matchid { get; set; }
        public short bowlingInnsnumber { get; set; }
        public System.Guid countryid { get; set; }
        public System.Guid playerid { get; set; }
        public Nullable<int> runs { get; set; }
        public Nullable<int> wickets { get; set; }
        public Nullable<int> maidens { get; set; }
        public Nullable<int> overs { get; set; }
        public Nullable<int> extras { get; set; }
        public System.DateTime lastupdated { get; set; }
    
        public virtual BowlingInn BowlingInns1 { get; set; }
        public virtual BowlingInn BowlingInn1 { get; set; }
    }
}
