//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CricketStats.Datalayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dismissal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dismissal()
        {
            this.BattingInns = new HashSet<BattingInn>();
        }
    
        public System.Guid dismissalid { get; set; }
        public string dismissalcode { get; set; }
        public string dismissaldesc { get; set; }
        public System.DateTime lastupdated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BattingInn> BattingInns { get; set; }
    }
}
