//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CricketStats.Datalayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Match
    {
        public System.Guid matchid { get; set; }
        public short matchnumber { get; set; }
        public System.Guid homecountryid { get; set; }
        public System.Guid awaycountryid { get; set; }
        public System.Guid venueid { get; set; }
        public System.Guid matchtypeid { get; set; }
        public Nullable<System.DateTime> matchstartdate { get; set; }
        public System.Guid tosswinnercountryid { get; set; }
        public System.DateTime lastupdated { get; set; }
    }
}
