//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CricketStats.Datalayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public System.Guid playerid { get; set; }
        public string playername { get; set; }
        public string playersurname { get; set; }
        public System.Guid countryid { get; set; }
        public System.DateTime dob { get; set; }
        public Nullable<bool> retired { get; set; }
        public System.DateTime lastupdated { get; set; }
    
        public virtual Country Country { get; set; }
    }
}
