//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CricketStats.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchType
    {
        public System.Guid matchtypeid { get; set; }
        public string matchtypename { get; set; }
        public System.DateTime lastupdated { get; set; }
    }
}
